### ISSUE TITLE
How to set static metadata

### ISSUE THREAD

**Issue by vassilisw** [Moonbase59/ices0#5]
Hi,
Is there a way to set metadata to a static string, (or even signalling to update like ices2), instead of showing the current song title?  

I've noticed that you're wondering in your code notes:
`usr1` signal is useful for debugging scripts, test our scripts behaviour when changing song or playlist ends, etc., So, yeah, keep it!

**Comment by SebAlbert** [comment]
You could use the perl or python plugin architecture. There is a hook (a function you have to implement in your perl or python module) called `ices_get_metadata` that is queried for the metadata at the beginning of each file being played out. You could just have it return your static string everytime.

See
https://github.com/Moonbase59/ices0/blob/cc3c26394f3245af984a787378cd371db354fbcc/conf/ices.pm.dist#L25-L28
https://github.com/Moonbase59/ices0/blob/cc3c26394f3245af984a787378cd371db354fbcc/conf/ices.py.dist#L26-L30

**Comment by vassilisw** [comment]
Yes! This will certainly do!
Excellent work by the way...
